apiVersion: skaffold/v4beta6
kind: Config
build:
  local:
    push: false
  artifacts:
    # - image: thomaslaich/hashsum-api
    #   context: ./apps/api
    #   docker:
    #     dockerfile: Dockerfile.dev
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    # - image: thomaslaich/hashsum-worker
    #   context: ./apps/worker
    #   docker:
    #     dockerfile: Dockerfile.dev
    #   sync:
    #     manual:
    #       - src: 'src/**/*.ts'
    #         dest: .
    - image: thomaslaich/hashsum-webapp
      context: .
      docker:
        dockerfile: apps/webapp/Dockerfile.dev
      sync:
        manual:
          - src: 'apps/webapp/src/**/*.ts'
            dest: .
          - src: 'apps/webapp/src/**/*.svelte'
            dest: .
deploy:
  kubectl: {}
