apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: api
          image: thomaslaich/hashsum-api
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: mq-cluster-ip-service
            - name: REDIS_PORT
              value: '6379'
            - name: AMQP_HOST
              value: mq-cluster-ip-service
            - name: AMQP_PORT
              value: '5672'
            - name: PG_USER
              value: postgres
            - name: PG_HOST
              value: postgres-cluster-ip-service
            - name: PG_DATABASE
              value: postgres
            - name: PG_PORT
              value: '5432'
            - name: PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
